Repository mysociety/whatdotheyknow-theme, pull requests merged in 2018-10, with the labels that each got.

#511 Preparation for header changes from core
  app/assets/stylesheets/responsive/custom.scss
  lib/views/general/_responsive_header.html.erb
Labels: 6 - awaiting deploy

#513 Add updated Home Office no-reply email
  lib/model_patches.rb
Labels: 6 - awaiting deploy

#515 [Core#4891] Quick fix
  lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb
Labels: 5 - awaiting review

#512 Prevent spam terms being used in requests
  lib/controller_patches.rb
  spec/integration/spam_terms_integration_spec.rb
Labels: 6 - awaiting deploy

#522 [#517] Fix broken ICO URL
  lib/views/help/about.html.erb
Labels: 6 - awaiting deploy

#528 [#523] Add anchor for backwards compatibility
  lib/views/help/privacy.html.erb
Labels: 6 - awaiting deploy

#521 [#4865] Add reCAPTCHA to the contact form
  lib/controller_patches.rb
  lib/views/help/_contact_form.html.erb
Labels: 3 - current sprint
