Repository mysociety/whatdotheyknow-theme, pull requests merged in 2022-08, with the labels that each got.

#1278 Create PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: awaiting-deploy, easier-admin, enable-volunteers

#1312 Fixes mySoc styleguide conflict
  lib/views/help/requesting.html.erb
Labels: awaiting-deploy

#1275 Add no reply emails for Tewkesbury BC and Publica Group
  lib/model_patches.rb
Labels: awaiting-review

#1287 Update intro section of how help page
  lib/views/help/how.html.erb
Labels: awaiting-review

#1288 [#1068] Update statistics in Internal Advice help
  lib/views/help/unhappy.html.erb
Labels: awaiting-review

#1314 Update requesting.html.erb
  lib/views/help/requesting.html.erb
Labels: awaiting-review

#1329 [#1328] Update ICO links for s14 and s43 in refusal advice
  config/refusal_advice/section_14_actions.yml.erb
  config/refusal_advice/section_43.yml.erb
  config/refusal_advice/section_43_actions.yml.erb
Labels: awaiting-review

#1330 [#818] Add special link for MapIt areas
  lib/views/public_body/_more_info.html.erb
Labels: bodies-database, user-experience
