Repository mysociety/whatdotheyknow-theme, pull requests merged in 2023-02, with the labels that each got.

#1520 Add help text about private requests to FOI officer page
  lib/views/help/officers.html.erb
Labels: help-pages

#1532 Fix broken anchor
  lib/views/help/requesting.html.erb
Labels: awaiting-deploy

#1580 [#1579] Add LB Bromley / OneTrust no-reply email
  lib/model_patches.rb
Labels: awaiting-deploy

#1577 Improve volunteer form spam detection
  lib/volunteer_contact_form.rb
Labels: awaiting-deploy

#1588 [#1587] Add new Sharepoint address to `model_patches.rb`
  lib/model_patches.rb
Labels: awaiting-review

#1604 Add Met Police no-reply address to `model_patches.rb`
  lib/model_patches.rb
Labels: awaiting-deploy
