Repository mysociety/whatdotheyknow-theme, pull requests merged in 2025-01, with the labels that each got.

#1953 [#1948] Fix ICO Criminal Offence data link
  lib/views/help/report_a_data_breach.html.erb
Labels: awaiting-deploy

#1947 Update _more_info.html.erb to support UCAS links
  lib/views/public_body/_more_info.html.erb
Labels: awaiting-deploy

#1949 Add additional email addresses for Microsoft notifications
  lib/model_patches.rb
Labels: awaiting-deploy

#1950 Update how.html.erb (professional advice and medical information)
  lib/views/help/how.html.erb
Labels: awaiting-deploy, safeguarding

#1952 [#1951] Update ICO advice links in refusal advice section 12 costs
  config/refusal_advice/section_12_actions.yml.erb
Labels: awaiting-deploy

#1956 Update _frontpage_videos.html.erb
  lib/views/general/_frontpage_videos.html.erb
Labels: awaiting-deploy

#1958 Update _frontpage_videos.html.erb
  lib/views/general/_frontpage_videos.html.erb
Labels: awaiting-review
