Repository mysociety/whatdotheyknow-theme, pull requests merged in 2025-04, with the labels that each got.

#1937 Exclude certain types of authorities from batch category picker
  lib/model_patches.rb
Labels: awaiting-review, reducing-the-burden-on-small-authorities

#1981 [#1980] Add address for NHSWLT to no-reply list
  lib/model_patches.rb
Labels: awaiting-review

#1989 Update principles.html.erb
  lib/views/help/principles.html.erb
Labels: awaiting-review, help-pages

#1992 [#1991, 1993, #1994] Add no-reply email for Ayrshire Councils (North, and South), and NUH.
  lib/model_patches.rb
Labels: awaiting-review
